name: Deploy                    
on:                             
  push:
    branches:
      - Development                        
jobs:                           
  build:
    runs-on: ubuntu-latest
    defaults : 
      run : 
        working-directory : ./frontend
    
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install AWS CLI
        run: pip3 install awscli --upgrade --user
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
          
      - name: Generate Environment Variables File for Production
        shell : bash
        env:
         REACT_APP_API_SERVER: ${{ secrets.REACT_APP_API_SERVER }}
         AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
         touch .env.production
         echo REACT_APP_API_SERVER="$REACT_APP_API_SERVER" >> .env.production
         echo AWS_ACCESS_KEY="$AWS_ACCESS_KEY" >> .env.production
         echo AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" >> .env.production   
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Check Node v          
        run: node -v
      
      - name: Install Dependencies  
        run: yarn

      - name: Build                 
        run: yarn build
      
      - name: Deploy
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://runningmate
  
  deploy-dev:
    name: Deploy(Dev)
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: http://runningmate.s3-website.ap-northeast-2.amazonaws.com
    steps:
      - uses: actions/checkout@v2
      - run: echo 'Developement deployment'
